version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "username" ]
    networks:
      - fastapi_network

  app:
    build:
      context: .
      dockerfile: Dockerfile_back
    container_name: fastapi_app
    restart: always
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/yourdatabase
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastapi_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    ports:
      - "8500:8500"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    networks:
      - fastapi_network


volumes:
  postgres_data:  

networks:
  fastapi_network:
    driver: bridge
