FROM python:3.12.3-slim

WORKDIR /app
COPY . .

RUN apt-get update && \
    # apt-get install -y build-essential libpq-dev && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

ENV PYTHONPATH=/app

CMD ["uvicorn", "back.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
