FROM python:3.12.3-slim

ARG CONTAINER_HOME
ENV CONTAINER_HOME=$CONTAINER_HOME

WORKDIR $CONTAINER_HOME

COPY back ./back
COPY requirements_back.txt ./requirements.txt

RUN apt-get update && \
    pip install --upgrade pip && \
    pip install -r ./requirements.txt

ARG FASTAPI_PORT
ENV FASTAPI_PORT=$FASTAPI_PORT

ENTRYPOINT uvicorn back.main:app --host 0.0.0.0 --port $FASTAPI_PORT
