version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  app:
    build:
      context: .
      dockerfile: Dockerfile_back
    container_name: fastapi_app
    restart: always
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/yourdatabase
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    depends_on:
      - db  
    networks:
      - fastapi_network

volumes:
  postgres_data:  

networks:
  fastapi_network:
    driver: bridge
