FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && pip install --upgrade pip && pip install poetry==1.8.3

COPY poetry.lock pyproject.toml /app/

RUN poetry install

COPY . .

EXPOSE 8500

ENV PYTHONPATH=/app

CMD ["poetry", "run", "python", "bot/main.py"]