[tool.poetry]
name = "reu-ds-club-task-validator"
version = "0.1.0"
description = ""
authors = ["artemmmichurin <amichurin@sbdagroup.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
